sonar.projectKey=tests-dsec
sonar.projectName=tests-dsec
sonar.projectVersion=1.0

sonar.sources=./

sonar.sourceEncoding=UTF-8
sonar.language=python
sonar.exclusions=**/venv/**, **/.github/**, **/docs/**, **/src/** 